defmodule PaperTiger.Resources.ApplicationFee do
  @moduledoc """
  Handles Application Fee resource endpoints.

  ## Endpoints

  - GET    /v1/application_fees/:id  - Retrieve application fee
  - GET    /v1/application_fees      - List application fees

  Note: Application fees are auto-generated by Stripe and cannot be created, updated, or deleted.

  ## Application Fee Object

      %{
        id: "fee_...",
        object: "application_fee",
        created: 1234567890,
        amount: 100,  # in cents
        currency: "usd",
        charge: "ch_...",
        refunded: false,
        amount_refunded: 0,
        metadata: %{},
        # ... other fields
      }
  """

  import PaperTiger.Resource

  alias PaperTiger.Store.ApplicationFees

  @doc """
  Retrieves an application fee by ID.
  """
  @spec retrieve(Plug.Conn.t(), String.t()) :: Plug.Conn.t()
  def retrieve(conn, id) do
    PaperTiger.Connect.without_account(fn ->
      case ApplicationFees.get(id) do
        {:ok, fee} ->
          fee
          |> maybe_expand(conn.params)
          |> then(&json_response(conn, 200, &1))

        {:error, :not_found} ->
          error_response(conn, PaperTiger.Error.not_found("application_fee", id))
      end
    end)
  end

  @doc """
  Lists all application fees with pagination.

  ## Parameters

  - limit - Number of items (default: 10, max: 100)
  - starting_after - Cursor for pagination
  - ending_before - Reverse cursor
  - charge - Filter by charge ID
  """
  @spec list(Plug.Conn.t()) :: Plug.Conn.t()
  def list(conn) do
    PaperTiger.Connect.without_account(fn ->
      pagination_opts = parse_pagination_params(conn.params)

      result =
        case Map.get(conn.params, :charge) do
          charge when is_binary(charge) and charge != "" ->
            charge
            |> ApplicationFees.find_by_charge()
            |> PaperTiger.List.paginate(Map.put(pagination_opts, :url, "/v1/application_fees"))

          _ ->
            ApplicationFees.list(pagination_opts)
        end

      json_response(conn, 200, result)
    end)
  end

  ## Private Functions
end
